telegram:
  token: TOKEN_HERE
  targetGroups:
    moodle_error:
      - some_chat_id
      - another_chat_id
tasks:
  moodle_landingpage:
    interval: 60
    enabled: true
  message_task:
    enabled: false